-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Kategoria CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS RuokaAine CASCADE;
DROP TABLE IF EXISTS RuokaLista CASCADE;